apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::111111111111:role/demo-us-east-120190321013644620800000008
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::1111111111111:role/PowerUser
      username: PowerUser:{{SessionName}}
      groups:
        - system:masters

  mapUsers: |

  mapAccounts: |

